### PR TITLE
Add ability to add own format (for example in bootstrap.php).

### PR DESCRIPTION
**Pull request by michallohnisky**

### CODE REVIEW

**Comment by michallohnisky** [comment]
@voda Bump.

**Comment by voda** [comment]
What should be the use case for this? The addon is meant to add html5 date/time inputs support.

**Comment by michallohnisky** [comment]
Nette Forms has great validators and we use them for frontend and for validating api input. Api sometimes need to accept different format. We could validate the field using pattern, but this library converts the string to datetime object and has min/max validators. That is why we want to use it instead of pattern.

**Comment by voda** [comment]
How about extracting the validation and convert functionality to a separate class? Would that work for you?

**Comment by michallohnisky** [comment]
I don't know, what you mean. Validation and convert functionality is closely bound with your DateInput control, so this change would need large refactoring. We use this component and other inputs from nette/form and it works for us nicely. I think, there is no need to divide it.

**Pull request closed without merging**
